GET https://localhost:5000/
###

GET https://localhost:5000/api/EventAttendance/h
###

POST https://localhost:5000/api/EventAttendance/Attend
Content-Type: application/json

{
    "Id": "d9a2785f-9427-431a-879f-bc22b205405d",
    "User_Id": "ad80f0e9-47c1-49c2-a883-2674117e81bc",
    "Event_Id": "ac1c489d-c090-49dc-b850-b827f1d1b049"
}
###

GET https://localhost:5000/api/EventAttendance/FindEventAttendees/ac1c489d-c090-49dc-b850-b827f1d1b049
###

GET https://localhost:5000/api/EventAttendance/DeleteEventAttendance/ac1c489d-c090-49dc-b850-b827f1d1b049/ad80f0e9-47c1-49c2-a883-2674117e81bc
###

// ee1ad764-2d47-4e22-a1b8-a72ef8ccdb72
// d9a2785f-9427-431a-879f-bc22b205405d
// 8e55404e-a104-4439-abb6-78590cc72f8d
// user id   , ad80f0e9-47c1-49c2-a883-2674117e81bc
// event id 1, ac1c489d-c090-49dc-b850-b827f1d1b049
// event id 2, dc20869e-0e40-4ba0-a4d5-ca68aa6e4578

/*
- ####attend an event you already attended
- list attendees only to event you planned/or are attending???
- ####only be able to delete attendance if it hasnt passed yet (change OnTime function to IsBeforeEvent)
- merge login so that only a logged in can view list of attendees
- only delete if logged in is the same as the user attendance being deleted
*/